# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Software Engineering For Scientific Computing
author: Henry Schreiner, Romain Teyssier
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: se-for-sci.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/se-for-sci/se-for-sci.github.io
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true

only_build_toc_files: true
exclude_patterns:
  - "**.*cache"
  - "**.ipynb_checkpoints"
  - "**.nox"
  - "**.pixi"
  - "**.virtual_documents"
  - .DS_Store
  - Thumbs.db
  - "**/_build"
  - "**/build"
  - notes

sphinx:
  extra_extensions:
    - sphinxcontrib.mermaid
  config:
    nb_execution_show_tb: True
    copybutton_prompt_text: '\$ '
    copybutton_prompt_is_regexp: true
    copybutton_only_copy_prompt_lines: true
    html_theme_options:
      navigation_with_keys: false
