name: se-for-sci
channels:
  - conda-forge
dependencies:
  - black
  - cattrs
  - ipykernel >=6.0
  - ipython >=8.0
  - ipywidgets
  - jupyter-book
  - jupyterlab >=3
  - matplotlib >=3.5
  - nb_conda_kernels
  - numpy >=1.20
  - pandas >=1.3
  - pip
  - pytest >7
  - python ==3.10.*
  - rich >=11
  - sphinxcontrib-mermaid
